import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { ToastProvider } from '@/providers/toast-provider';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
